import type { Locale, ProjectStatus, ProjectType } from "@/lib/types";

export const copy = {
  de: {
    langName: "Deutsch",
    ctaEnquire: "Projekt anfragen",
    ctaProjects: "Referenzprojekte",
    ctaServices: "Leistungen",
    skip: "Zum Inhalt",
    demo: "Demoseite",
    heroKicker: "01  /  Brandschutz für BESS",
    heroTitle: "Brandschutz für Batteriespeicher.",
    heroLede:
      "Prüfbare Nachweise für Projektentwickler und Betreiber — von der thermischen Ereignisanalyse bis zur Behördengenehmigung.",
    stats: [
      { value: "52", label: "BESS-Projekte" },
      { value: "2,6 GWh", label: "begleitete Kapazität" },
      { value: "7", label: "Länder in der EU+" },
      { value: "2018", label: "unabhängig seit" },
    ],
    servicesKicker: "02  /  Leistungen",
    servicesTitle: "Was wir nachweisen.",
    servicesLede:
      "Kein Produktverkauf. Keine Löschanlage von der Stange. Engineering, das Bauaufsicht, Feuerwehr und Versicherer prüfen können.",
    methodKicker: "03  /  Methodik",
    methodTitle: "Fünf Schritte, ein Nachweisordner.",
    method: [
      {
        n: "01",
        t: "Gefährdung",
        d: "Chemie, Aufstellung, Nachbarschaft, Netzkopplung. Was wirklich eskalieren kann.",
      },
      {
        n: "02",
        t: "Konzept",
        d: "Schutzziele, Abstände, Brandabschnitte. Sprache der Bauordnung, nicht des Datenblatts.",
      },
      {
        n: "03",
        t: "Ereignis",
        d: "Thermal Runaway, Gas, Wärme, Löschung. Hüllkurven statt Hoffnung.",
      },
      {
        n: "04",
        t: "Genehmigung",
        d: "Einreichstrategie, Termine, Erwiderungen. Auflagen bis Inbetriebnahme.",
      },
      {
        n: "05",
        t: "Betrieb",
        d: "Alarmstufen, Übungen, Änderungen. Das Konzept muss fahrbar sein.",
      },
    ],
    projectsKicker: "04  /  Referenzen",
    projectsTitle: "50+ Speicherprojekte, nachweisbar.",
    projectsLede:
      "Freifläche, Hybrid, Netzbooster, Industrie. Deutschland zuerst, Europa dort, wo dieselben Nachweise gelten.",
    projectsAll: "Alle Projekte",
    whyKicker: "05  /  Haltung",
    whyTitle: "Unabhängig vom Hersteller.",
    why: [
      {
        t: "Keine Hardware-Provision",
        d: "Wir verkaufen keine Container, keine Löschanlage, keine Zellen. Empfehlungen bleiben nachvollziehbar.",
      },
      {
        t: "Eine Sprache für alle Stellen",
        d: "Bauamt, Feuerwehr, Versicherer, Netzbetreiber lesen denselben Ordner — nicht drei widersprüchliche PDFs.",
      },
      {
        t: "Früh im FEED, nicht erst im Einwand",
        d: "Abstände und Löschwasser entscheiden Flächen. Wer das nach der Pacht klärt, zahlt doppelt.",
      },
    ],
    contactKicker: "06  /  Anfrage",
    contactTitle: "Projektstand schicken. Wir antworten in zwei Werktagen.",
    contactLede:
      "MW, MWh, Standort, Phase. Kein Vertriebscall — ein Ingenieur liest die Anfrage.",
    footerNav: "Navigation",
    footerOffices: "Büros",
    footerLegal: "Rechtliches",
    imprint: "Impressum (Demo)",
    privacy: "Datenschutz (Demo)",
    footerNote:
      "Demoseite einer Brandschutz-Ingenieurberatung für Batteriespeicher. Keine echte Mandatsannahme.",
    servicesPage: {
      kicker: "Leistungen",
      title: "Engineering, das eine Behörde gegenzeichnen kann.",
      lede: "Sechs Leistungsbilder. Jedes endet mit einem Dokument, das Sie einreichen, nicht mit einer Folie.",
      deliverTitle: "Typische Liefergegenstände",
      deliver: [
        "Brandschutzkonzept (Bauvorlage)",
        "Thermische Ereignisanalyse",
        "Lösch- und Detektionskonzept",
        "Löschwasser- und Rückhaltenachweis",
        "GAP-Bericht NFPA 855 / VdS 3103",
        "Stellungnahme Versicherer",
        "Einsatzunterlage Feuerwehr",
        "Betriebliches Brandschutzkonzept",
      ],
    },
    projectsPage: {
      kicker: "Projekte",
      title: "Referenzen nach Land, Typ und Phase.",
      lede: "52 dokumentierte BESS-Mandate. Filterbar. Kapazitäten und Scopes wie im Nachweisordner — ohne Kundenlogos, die wir nicht zeigen dürfen.",
      all: "Alle",
      mapTitle: "Einsatzraum EU+",
      mapLede: "Schwerpunkt Deutschland. Mandate dort, wo NFPA, VdS und lokale Bauordnung zusammenlaufen.",
      empty: "Keine Projekte für diese Kombination.",
      reset: "Filter zurücksetzen",
      capacity: "Kapazität",
      power: "Leistung",
      scope: "Leistungsumfang",
    },
    aboutPage: {
      kicker: "Über uns",
      title: "Ingenieure für ein Risiko, das Datenblätter nicht tragen.",
      lede: "IONEX ist 2018 in Essen entstanden, als die ersten großen deutschen Freiflächen-BESS an die Bauaufsicht gingen — und feststellte, dass klassischer Industriebau-Brandschutz die Chemie nicht abbildet.",
      storyTitle: "Warum wir existieren",
      story: [
        "Ein Batteriespeicher ist kein Lager und kein Trafohäuschen. Thermal Runaway, Gasphase und Containerdichte erzeugen Szenarien, die weder die Muster-Industriebaurichtlinie noch ein Sprinklerdatenblatt allein lösen.",
        "Wir arbeiten als unabhängige Fachplaner: Brandschutz, thermische Ereignisse, Genehmigung. Kein EPC, kein Produktvertrieb. Mandanten sind Projektentwickler, Betreiber, Investoren und gelegentlich Behörden, die eine zweite Meinung brauchen.",
        "Büro Essen (Ruhr, Netz, Industrie) und München (Südschiene). Projekte von Schleswig-Holstein bis Oberösterreich, mit denselben Nachweisstandards.",
      ],
      teamTitle: "Leitung",
      independTitle: "Unabhängigkeit",
      independ:
        "IONEX nimmt keine Vertriebsprovisionen von Zellen-, Container- oder Löschherstellern. Bewertungen von Systemen sind schriftlich begründet und an Schutzziele gebunden.",
    },
    contactPage: {
      kicker: "Kontakt",
      title: "Anfrage zum Speicherprojekt.",
      lede: "Für Entwickler und Betreiber. Bitte MW, MWh, Standort und Phase angeben — wir können sonst nicht sinnvoll antworten.",
      successTitle: "Eingang bestätigt.",
      successBody:
        "Ein Ingenieur antwortet innerhalb von zwei Werktagen. Bei laufendem Genehmigungsverfahren bitte Auflagen oder Einwendungstext mitliefern.",
      errorTitle: "Anfrage nicht gesendet.",
      errorBody: "Netzwerk oder Validierung. Pflichtfelder prüfen und erneut senden.",
      another: "Weitere Anfrage",
      privacyNote:
        "Mit dem Senden willigen Sie ein, dass wir die Angaben zur Bearbeitung der Anfrage verwenden. Kein Newsletter.",
    },
    form: {
      name: "Name",
      company: "Firma",
      role: "Rolle",
      email: "E-Mail",
      phone: "Telefon",
      country: "Land / Standort",
      mw: "Leistung (MW)",
      mwh: "Kapazität (MWh)",
      phase: "Projektphase",
      message: "Sachverhalt",
      submit: "Anfrage senden",
      sending: "Senden …",
      required: "Pflichtfeld",
      emailInvalid: "Bitte eine gültige E-Mail angeben.",
      roles: [
        { value: "developer", label: "Projektentwickler" },
        { value: "operator", label: "Betreiber" },
        { value: "investor", label: "Investor / Asset Manager" },
        { value: "epc", label: "EPC / Generalplaner" },
        { value: "insurer", label: "Versicherer" },
        { value: "authority", label: "Behörde" },
        { value: "other", label: "Sonstiges" },
      ],
      phases: [
        { value: "site", label: "Flächensicherung" },
        { value: "permit", label: "Genehmigung" },
        { value: "feed", label: "FEED / Detailplanung" },
        { value: "build", label: "Bau" },
        { value: "ops", label: "Betrieb / Repowering" },
      ],
      messagePh:
        "Standort, Chemie soweit bekannt, offene Behördenfragen, Termin.",
    },
    types: {
      standalone: "Freiflächen-BESS",
      "pv-hybrid": "PV-Hybrid",
      "wind-hybrid": "Wind-Hybrid",
      industrie: "Industrie",
      netzbooster: "Netzbooster",
      hinterzaehler: "Hinter-Zähler",
    } satisfies Record<ProjectType, string>,
    status: {
      "in-betrieb": "In Betrieb",
      genehmigt: "Genehmigt",
      "in-planung": "In Planung",
    } satisfies Record<ProjectStatus, string>,
    notFound: {
      title: "Seite nicht gefunden.",
      body: "Die Adresse existiert nicht. Zurück zur Startseite.",
      home: "Home",
    },
  },
  en: {
    langName: "English",
    ctaEnquire: "Request a review",
    ctaProjects: "Reference projects",
    ctaServices: "Services",
    skip: "Skip to content",
    demo: "Demo site",
    heroKicker: "01  /  Fire safety for BESS",
    heroTitle: "Fire safety for battery storage.",
    heroLede:
      "Reviewable evidence for developers and operators — from thermal event analysis to the permit.",
    stats: [
      { value: "52", label: "BESS projects" },
      { value: "2.6 GWh", label: "capacity advised" },
      { value: "7", label: "countries in EU+" },
      { value: "2018", label: "independent since" },
    ],
    servicesKicker: "02  /  Services",
    servicesTitle: "What we evidence.",
    servicesLede:
      "No product sales. No off-the-shelf suppression package. Engineering that building control, the fire service and insurers can actually check.",
    methodKicker: "03  /  Method",
    methodTitle: "Five steps, one evidence pack.",
    method: [
      {
        n: "01",
        t: "Hazard",
        d: "Chemistry, layout, neighbours, grid coupling. What can actually escalate.",
      },
      {
        n: "02",
        t: "Concept",
        d: "Objectives, setbacks, compartments. Building-code language, not datasheet language.",
      },
      {
        n: "03",
        t: "Event",
        d: "Thermal runaway, gas, heat, suppression. Envelopes, not hope.",
      },
      {
        n: "04",
        t: "Permit",
        d: "Filing strategy, meetings, responses. Conditions through commissioning.",
      },
      {
        n: "05",
        t: "Operations",
        d: "Alarm stages, drills, change. The concept has to be runnable.",
      },
    ],
    projectsKicker: "04  /  References",
    projectsTitle: "50+ storage projects, evidenced.",
    projectsLede:
      "Standalone, hybrid, grid booster, industrial. Germany first; Europe where the same evidence applies.",
    projectsAll: "All projects",
    whyKicker: "05  /  Position",
    whyTitle: "Independent of the OEM.",
    why: [
      {
        t: "No hardware commission",
        d: "We do not sell containers, suppression, or cells. Recommendations stay traceable.",
      },
      {
        t: "One language for every desk",
        d: "Building control, fire service, insurer and grid operator read the same pack — not three conflicting PDFs.",
      },
      {
        t: "In FEED, not in the objection",
        d: "Setbacks and fire water decide the plot. Settling that after the lease is paid twice.",
      },
    ],
    contactKicker: "06  /  Enquiry",
    contactTitle: "Send the project state. We reply in two working days.",
    contactLede:
      "MW, MWh, site, phase. No sales call — an engineer reads the enquiry.",
    footerNav: "Navigation",
    footerOffices: "Offices",
    footerLegal: "Legal",
    imprint: "Imprint (demo)",
    privacy: "Privacy (demo)",
    footerNote:
      "Demo site for a battery-storage fire-safety engineering practice. No real engagement is formed.",
    servicesPage: {
      kicker: "Services",
      title: "Engineering an authority can countersign.",
      lede: "Six scopes. Each ends in a document you file, not a slide.",
      deliverTitle: "Typical deliverables",
      deliver: [
        "Fire-safety concept (building submission)",
        "Thermal event analysis",
        "Detection and suppression concept",
        "Fire-water and containment evidence",
        "Gap report NFPA 855 / VdS 3103",
        "Insurer opinion",
        "Fire-service response pack",
        "Operational fire-safety concept",
      ],
    },
    projectsPage: {
      kicker: "Projects",
      title: "References by country, type and phase.",
      lede: "52 documented BESS mandates. Filterable. Capacities and scopes as in the evidence pack — without client logos we cannot show.",
      all: "All",
      mapTitle: "Operating area EU+",
      mapLede: "Germany first. Mandates where NFPA, VdS and local building code meet.",
      empty: "No projects for this combination.",
      reset: "Reset filters",
      capacity: "Capacity",
      power: "Power",
      scope: "Scope",
    },
    aboutPage: {
      kicker: "About",
      title: "Engineers for a risk datasheets do not carry.",
      lede: "IONEX was formed in Essen in 2018, when the first large German standalone BESS hit building control — and found that classic industrial fire design does not capture the chemistry.",
      storyTitle: "Why we exist",
      story: [
        "A battery store is not a warehouse and not a transformer kiosk. Thermal runaway, gas phase and container density create scenarios that neither industrial-building guidance nor a sprinkler datasheet solves alone.",
        "We work as independent specialist designers: fire safety, thermal events, permitting. Not an EPC, not a product vendor. Clients are developers, operators, investors, and occasionally authorities who need a second opinion.",
        "Office Essen (Ruhr, grid, industry) and Munich (southern corridor). Projects from Schleswig-Holstein to Upper Austria, under the same evidence standards.",
      ],
      teamTitle: "Leadership",
      independTitle: "Independence",
      independ:
        "IONEX takes no sales commission from cell, container or suppression manufacturers. System judgements are written down and tied to protection objectives.",
    },
    contactPage: {
      kicker: "Contact",
      title: "Enquiry on a storage project.",
      lede: "For developers and operators. Please include MW, MWh, site and phase — otherwise we cannot answer usefully.",
      successTitle: "Received.",
      successBody:
        "An engineer replies within two working days. For live permitting, attach conditions or the objection text.",
      errorTitle: "Enquiry not sent.",
      errorBody: "Network or validation. Check required fields and send again.",
      another: "Another enquiry",
      privacyNote:
        "By sending you agree we use the data to handle the enquiry. No newsletter.",
    },
    form: {
      name: "Name",
      company: "Company",
      role: "Role",
      email: "Email",
      phone: "Phone",
      country: "Country / site",
      mw: "Power (MW)",
      mwh: "Capacity (MWh)",
      phase: "Project phase",
      message: "Facts",
      submit: "Send enquiry",
      sending: "Sending…",
      required: "Required",
      emailInvalid: "Enter a valid email.",
      roles: [
        { value: "developer", label: "Project developer" },
        { value: "operator", label: "Operator" },
        { value: "investor", label: "Investor / asset manager" },
        { value: "epc", label: "EPC / lead designer" },
        { value: "insurer", label: "Insurer" },
        { value: "authority", label: "Authority" },
        { value: "other", label: "Other" },
      ],
      phases: [
        { value: "site", label: "Site control" },
        { value: "permit", label: "Permitting" },
        { value: "feed", label: "FEED / detailed design" },
        { value: "build", label: "Construction" },
        { value: "ops", label: "Operations / repowering" },
      ],
      messagePh:
        "Site, chemistry if known, open authority questions, timing.",
    },
    types: {
      standalone: "Standalone BESS",
      "pv-hybrid": "PV hybrid",
      "wind-hybrid": "Wind hybrid",
      industrie: "Industrial",
      netzbooster: "Grid booster",
      hinterzaehler: "Behind-the-meter",
    } satisfies Record<ProjectType, string>,
    status: {
      "in-betrieb": "In operation",
      genehmigt: "Permitted",
      "in-planung": "In planning",
    } satisfies Record<ProjectStatus, string>,
    notFound: {
      title: "Page not found.",
      body: "This address does not exist. Back to home.",
      home: "Home",
    },
  },
} as const;

export type Copy = (typeof copy)[Locale];
